apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: product-catalog-client-asmc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: product-catalog-client-asmc
    app.kubernetes.io/part-of: product-catalog
  name: product-catalog-client-asmc
  namespace: gnunn-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: product-catalog-client-asmc
    weight: null
status: {}
